"""initial tables

Revision ID: 8584d7ff470e
Revises: 
Create Date: 2026-03-10 01:05:06.972599
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8584d7ff470e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_file', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('telegram_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_entities_telegram_id'), 'telegram_entities', ['telegram_id'], unique=False)
    op.create_table('clone_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('destination_entity_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source_title', sa.String(length=256), nullable=False),
    sa.Column('destination_title', sa.String(length=256), nullable=False),
    sa.Column('account_phone', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('import_history', sa.Boolean(), nullable=False),
    sa.Column('monitor_new', sa.Boolean(), nullable=False),
    sa.Column('send_interval_ms', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('temp_directory', sa.String(length=512), nullable=False),
    sa.Column('oversized_policy', sa.String(length=20), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('incompatible_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ),
    sa.ForeignKeyConstraint(['destination_entity_id'], ['telegram_entities.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['telegram_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_jobs_status'), 'clone_jobs', ['status'], unique=False)
    op.create_table('clone_job_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('grouped_id', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('media_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('destination_message_id', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clone_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_job_items_status'), 'clone_job_items', ['status'], unique=False)
    op.create_index('ix_job_items_job_msg', 'clone_job_items', ['job_id', 'source_message_id'], unique=True)
    op.create_index('ix_job_items_job_status', 'clone_job_items', ['job_id', 'status'], unique=False)
    op.create_table('clone_job_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clone_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_job_logs_created_at'), 'clone_job_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_clone_job_logs_level'), 'clone_job_logs', ['level'], unique=False)
    op.create_index('ix_job_logs_job_created', 'clone_job_logs', ['job_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_logs_job_created', table_name='clone_job_logs')
    op.drop_index(op.f('ix_clone_job_logs_level'), table_name='clone_job_logs')
    op.drop_index(op.f('ix_clone_job_logs_created_at'), table_name='clone_job_logs')
    op.drop_table('clone_job_logs')
    op.drop_index('ix_job_items_job_status', table_name='clone_job_items')
    op.drop_index('ix_job_items_job_msg', table_name='clone_job_items')
    op.drop_index(op.f('ix_clone_job_items_status'), table_name='clone_job_items')
    op.drop_table('clone_job_items')
    op.drop_index(op.f('ix_clone_jobs_status'), table_name='clone_jobs')
    op.drop_table('clone_jobs')
    op.drop_index(op.f('ix_telegram_entities_telegram_id'), table_name='telegram_entities')
    op.drop_table('telegram_entities')
    op.drop_table('telegram_accounts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
