"""add_payments_table

Revision ID: e6160746c42c
Revises: 3f048ae388ae
Create Date: 2026-03-10 02:29:18.939965
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e6160746c42c'
down_revision: Union[str, None] = '3f048ae388ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tracking_ref', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mundpay_order_id', sa.String(length=128), nullable=True),
    sa.Column('customer_name', sa.String(length=256), nullable=True),
    sa.Column('customer_email', sa.String(length=256), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clone_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tracking_ref'), 'payments', ['tracking_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tracking_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
